name: Tests
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Run tests
        run: go test -v -race ./...
  mod:
    name: Check that `go mod tidy` is clean
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Check
        run: |
          go mod tidy
          git diff --name-only --exit-code || (echo "Please run 'go mod tidy'."; exit 1)
